# Número total de accidentes registrados
select COUNT(DISTINCT ?accidente) AS ?numero
Where{
  ?accidente a <http://vocab.linkeddata.es/datosabiertos/def/transporte/accidentalidad-trafico#Accidente>. 
}

# 100 accidentes en los que se ha visto implicado un peatón
PREFIX accidente: <http://vocab.linkeddata.es/datosabiertos/def/transporte/accidentalidad-trafico#>
select distinct ?uri ?comentario ?fecha  (group_concat(distinct ?calle;separator=" - ")) as ?calle
where {
     ?uri a accidente:Accidente;
     	accidente:afectado ?afectado;
     	rdfs:comment ?comentario;
     	s:streetAddress ?calle;
     	dcterms:created ?fecha.
     ?afectado accidente:rolEnVehiculo/skos:notation	"peaton"
} LIMIT 100
