PREFIX pproc: <http://contsem.unizar.es/def/sector-publico/pproc#>
PREFIX s: <http://schema.org/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX pc: <http://purl.org/procurement/public-contracts#>

SELECT distinct ?uriCont ?formalizedDate ?type  
WHERE {
  ?uriCont a pproc:Contract;
  pc:tender ?tender;
  a ?type;
  pproc:contractObject ?contractObject.
  ?tender pproc:formalizedDate ?formalizedDate;
  pc:supplier ?supplier.
  ?supplier s:name ?name .
  FILTER (regex(?name, "XXX", "i"))
} ORDER BY ?formalizedDate
