PREFIX pproc: <http://contsem.unizar.es/def/sector-publico/pproc#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT count (distinct ?uriCont) ?title ?uriCont 
WHERE {
  ?uriCont a <http://contsem.unizar.es/def/sector-publico/pproc#Contract>;
  pproc:managingDepartment ?managingDepartment.
  ?managingDepartment dcterms:title ?title
} 
ORDER BY  (count (distinct ?uriCont))
