PREFIX pproc: <http://contsem.unizar.es/def/sector-publico/pproc#>
PREFIX s: <http://schema.org/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX pc: <http://purl.org/procurement/public-contracts#>

SELECT SUM(distinct ?currencyValue) as ?total 
WHERE {
  ?uriCont a pproc:Contract;
  pc:tender ?tender;
  pproc:contractObject/pproc:contractEconomicConditions/pproc:budgetPrice ?budgetPrice;
  pproc:contractProcedureSpecifications ?contProcSpec;
  pproc:managingDepartment ?managingDepartment.
  ?managingDepartment dcterms:title ?title.
  ?tender pproc:formalizedDate ?formalizedDate;
  pc:offeredPrice ?offeredPrice.
  ?offeredPrice gr:hasCurrencyValue ?currencyValue;
  gr:valueAddedTaxIncluded ?taxIncluded.
  FILTER ( (?taxIncluded) AND regex(?title, "Servicio de ", "i")) 
}
